### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chutou** [chenglou/react-dash#12]
error info: 
![qq 20151124145517](https://cloud.githubusercontent.com/assets/12060857/11359918/509e480c-92bb-11e5-9ff6-e9837821419c.jpg)

**Comment by chenglou** [comment]
Hey! Sorry for the delayed reply. A per #10, this repo's officially deprecated, because Dash has taken on the task of officially supporting React docs =). You can simply download them from the official docs section now.
