### ISSUE TITLE
Please update react-dash to version 0.13.1

### ISSUE THREAD

**Issue by CaptainFeng** [chenglou/react-dash#3]
There are many differences between 0.12.2 and 0.13.1.
Please update react-dash to 0.13.1

**Comment by chenglou** [comment]
Will do tomorrow!

**Comment by msutherl** [comment]
@chenglou eagerly awaiting :wink:

**Comment by iansinnott** [comment]
I think if you re-run `./build.sh` from within the repo it will fetch the latest docs. I just installed the docs for the first time and they look up to date.

**Comment by chenglou** [comment]
Yeah, I've made the whole building thing as hassle-free as possible =)

**Comment by CaptainFeng** [comment]
Thank you. It has been merged.
