### ISSUE TITLE
Any reason you don't publish to the official docs list?

### ISSUE THREAD

**Issue by iansinnott** [chenglou/react-dash#4]
The title is the question. Just wondering why you haven't added this docset to the official docs list. It would be a great addition.

**Comment by chenglou** [comment]
Ehm, I thought @Kapeli decided that? Not sure how this works.

**Comment by Kapeli** [comment]
All user contributed docsets go to Preferences > Downloads > User Contributed. Otherwise, I'd end up having to support all the abandoned docsets.

**Comment by chenglou** [comment]
That makes sense. @iansinnott: how dash contribution works is that I generate the new docs here and copy paste the final bundle to my fork of https://github.com/Kapeli/Dash-User-Contributions, then submit a PR against that.

Right now this is a very easy process and I've documented it in the README. Takes only five minutes so I'm keeping this updated when I can. But @Kapeli if you ever become a react addict, feel free to include it in the officially supported docs =P.

**Comment by Kapeli** [comment]
React is the most-requested docset, so I'll definitely have to support it officially at some point. Right now I'm focusing on adding features instead of docsets, but I'll get to it eventually.

**Comment by iansinnott** [comment]
@Kapeli Cool, all good news it sounds like. I'm in full support of new features over docsets since we can make docsets ourselves (btw thanks @chenglou). But it's also good to hear that it will be included at some point. Manually installing docsets isn't the issue it's just having to update them by hand that presents a lot of friction
