### ISSUE TITLE
"Official" React docset

### ISSUE THREAD

**Issue by Kapeli** [chenglou/react-dash#9]
Hi @chenglou. This is just a heads-up that a React docset made by me will be released in the next Dash update. Please let me know what you would like to happen with your React docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/React.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by chenglou** [comment]
Oh man this is awesome and way more detailed than my version. The font seems not to have been preserved though?

**Comment by Kapeli** [comment]
Good catch. Should be fixed now (redownload).

**Comment by chenglou** [comment]
Hmm doesn't seem to have changed? Maybe I should wait a few minutes

**Comment by Kapeli** [comment]
Forgot to mention you need to remove and re-add the docset in Dash.

**Comment by chenglou** [comment]
Yeah I did

**Comment by Kapeli** [comment]
Hmm. Have you tried refreshing? (CMD+R)

**Comment by chenglou** [comment]
I just checked the package content/opened the offline page and it looks fine. However, directly in Dash 3 (just got it yesterday btw, great stuff =)) it still displays the wrong font:

<img width="1266" alt="screenshot 2015-07-06 21 20 24" src="https://cloud.githubusercontent.com/assets/1909539/8538667/d5d75f32-2424-11e5-9540-fffdc553e559.png">

Is it possible that the new annotation feature is interfering?

**Comment by Kapeli** [comment]
Hmm. No idea what's going on to be honest. The fonts look so similar to me that I don't think it's worth looking into further. Do fonts work for the docset you made?

**Comment by chenglou** [comment]
Oh wait, mine don't either. Probably some weird global styles. Doesn't matter then!

Thanks a lot for doing this. Now I can deprecate this repo in peace =)

**Comment by chenglou** [comment]
I see that this is in. Thanks so much! Deprecating this library now =)

**Comment by hoodwink73** [comment]
I use Dash 2 and I can neither see the official React doesn't nor the user contribution one? Any reason why Dash 2 cannot have the official React docset?

**Comment by chenglou** [comment]
You sure you don't see it in All Docsets?

**Comment by Kapeli** [comment]
React was added in Dash 3, so it's not available in Dash 2 (none of the new docsets are).

**Comment by hoodwink73** [comment]
@Kapeli Isn't it just nudging the user to get Dash 3, which is a paid upgrade. Any technical reason?

**Comment by Kapeli** [comment]
The reason is that I can't commit to checking new docsets for backwards compatibility with Dash 2.

**Comment by hoodwink73** [comment]
Fair enough. Thanks for Dash. It offers great value.
